// ── Current User ───────────────────────────────────────────────
export const currentUser = {
  id: 'u001',
  name: 'Juan C. Dela Cruz',
  firstName: 'Juan',
  initials: 'JD',
  email: 'juan.delacruz@email.com',
  phone: '+63 912 345 6789',
  address: '123 Rizal Street, Davao City',
  studentId: 'ADDU-2015-03247',
  degree: 'BS Computer Science',
  batch: 'Class of 2015',
  role: 'Alumni',
  job: 'Software Engineer, Tech Corp PH',
  totalDonated: 15500,
  campaignsSupported: 4,
  lastDonation: 'February 12, 2026',
};

export const adminUser = {
  id: 'a001',
  name: 'Dr. Elena Villanueva',
  initials: 'EV',
  email: 'evillanueva@addu.edu.ph',
  role: 'Admin',
};

// ── Campaigns ──────────────────────────────────────────────────
export const campaigns = [
  {
    id: 'c001',
    title: 'AdDU Excellence Scholarship Fund',
    description: 'Help deserving students access world-class education at Ateneo de Davao. Your donation directly funds tuition, books, and living allowances.',
    category: 'Scholarship',
    goal: 500000,
    raised: 312000,
    donors: 148,
    deadline: 'April 30, 2026',
    urgent: true,
    color: '#4169E1',
    image: 'scholarship',
    featured: true,
  },
  {
    id: 'c002',
    title: 'New Science Laboratory Equipment',
    description: 'Upgrade the physics, chemistry, and biology labs with modern equipment that meets international standards for STEM education.',
    category: 'Infrastructure',
    goal: 1000000,
    raised: 687000,
    donors: 203,
    deadline: 'June 15, 2026',
    urgent: false,
    color: '#2337C6',
    image: 'lab',
    featured: true,
  },
  {
    id: 'c003',
    title: 'Student Emergency Relief Fund',
    description: 'Immediate financial assistance for students and families affected by natural disasters or sudden hardship.',
    category: 'Relief',
    goal: 200000,
    raised: 178000,
    donors: 312,
    deadline: 'March 31, 2026',
    urgent: true,
    color: '#ef4444',
    image: 'relief',
    featured: false,
  },
  {
    id: 'c004',
    title: 'Campus Sustainability Initiative',
    description: 'Solar panels, rainwater collection, and green spaces to make AdDU a model for environmental responsibility.',
    category: 'Environment',
    goal: 300000,
    raised: 145000,
    donors: 87,
    deadline: 'May 20, 2026',
    urgent: false,
    color: '#10b981',
    image: 'green',
    featured: false,
  },
  {
    id: 'c005',
    title: 'Sports & Athletics Program',
    description: 'Fund uniforms, equipment, and tournament fees for the Ateneo Blue Knights. Help our athletes compete nationally.',
    category: 'Sports',
    goal: 150000,
    raised: 92000,
    donors: 64,
    deadline: 'April 10, 2026',
    urgent: false,
    color: '#f59e0b',
    image: 'sports',
    featured: false,
  },
];

// ── Donors (Top) ───────────────────────────────────────────────
export const topDonors = [
  { rank:1, initials:'MS', name:'Dr. Maria Santos',       batch:'Batch 2000', amount:50000, campaigns:3, badge:'Platinum' },
  { rank:2, initials:'CR', name:'Engr. Carlos Reyes',     batch:'Batch 2005', amount:35000, campaigns:4, badge:'Gold' },
  { rank:3, initials:'JD', name:'Juan C. Dela Cruz',      batch:'Batch 2015', amount:15500, campaigns:4, badge:'Silver' },
  { rank:4, initials:'AL', name:'Atty. Angela Lim',       batch:'Batch 2010', amount:12000, campaigns:2, badge:'Silver' },
  { rank:5, initials:'PG', name:'Dr. Patrick Gonzalez',   batch:'Batch 2008', amount:10000, campaigns:5, badge:'Silver' },
  { rank:6, initials:'RL', name:'Rosa Luna',              batch:'Batch 2019', amount:8500,  campaigns:2, badge:'Bronze' },
  { rank:7, initials:'BT', name:'Ben Torres',             batch:'Batch 2014', amount:7200,  campaigns:3, badge:'Bronze' },
  { rank:8, initials:'SB', name:'Sofia Batara',           batch:'Batch 2012', amount:6000,  campaigns:1, badge:'Bronze' },
  { rank:9, initials:'MA', name:'Marco Aquino',           batch:'Batch 2016', amount:5500,  campaigns:2, badge:'Bronze' },
  { rank:10,initials:'RV', name:'Rachel Villanueva',      batch:'Batch 2018', amount:4800,  campaigns:3, badge:'Bronze' },
];

// ── Monthly Chart Data ─────────────────────────────────────────
export const monthlyData = [
  { month:'Sep', amount:145000 },
  { month:'Oct', amount:198000 },
  { month:'Nov', amount:162000 },
  { month:'Dec', amount:287000 },
  { month:'Jan', amount:221000 },
  { month:'Feb', amount:312000 },
];

// ── Events ────────────────────────────────────────────────────
export const events = [
  {
    id: 'ev001',
    title: 'Alumni Grand Homecoming 2026',
    description: 'Annual reunion for all AdDU alumni. Thanksgiving mass, campus tour, cultural show, and grand dinner.',
    date: '2026-03-15',
    dateLabel: 'March 15, 2026',
    time: '9:00 AM – 5:00 PM',
    location: 'Finster Auditorium, AdDU Campus',
    type: 'Reunion',
    attending: 348,
    rsvpd: true,
    featured: true,
    color: '#4169E1',
  },
  {
    id: 'ev002',
    title: 'Annual Fund Drive Kickoff',
    description: 'Launch event for the 2026 Annual Fund Drive. Meet the team, learn about campaigns, and be the first to donate.',
    date: '2026-03-28',
    dateLabel: 'March 28, 2026',
    time: '2:00 PM – 5:00 PM',
    location: 'Abreeza Mall Events Hall, Davao',
    type: 'Fundraiser',
    attending: 120,
    rsvpd: false,
    featured: false,
    color: '#2337C6',
  },
  {
    id: 'ev003',
    title: 'Career & Networking Summit',
    description: 'Connect with alumni across industries. Career talks, job fair booths, and mentorship matching.',
    date: '2026-04-05',
    dateLabel: 'April 5, 2026',
    time: '9:00 AM – 4:00 PM',
    location: 'SMX Convention Center, Davao',
    type: 'Networking',
    attending: 215,
    rsvpd: false,
    featured: false,
    color: '#4CC9F0',
  },
  {
    id: 'ev004',
    title: 'Scholarship Awarding Ceremony',
    description: 'Celebrate the recipients of scholarship grants funded by alumni donations. Meet the students you are supporting.',
    date: '2026-04-20',
    dateLabel: 'April 20, 2026',
    time: '10:00 AM – 12:00 PM',
    location: 'AdDU Gym, Main Campus',
    type: 'Ceremony',
    attending: 180,
    rsvpd: false,
    featured: false,
    color: '#f59e0b',
  },
  {
    id: 'ev005',
    title: 'Batch 2015 Silver Mini-Reunion',
    description: '10-year anniversary for the Class of 2015. Reconnect with batchmates and reminisce.',
    date: '2026-05-10',
    dateLabel: 'May 10, 2026',
    time: '6:00 PM – 10:00 PM',
    location: 'Marco Polo Hotel, Davao',
    type: 'Reunion',
    attending: 64,
    rsvpd: true,
    featured: false,
    color: '#a855f7',
  },
];

// ── Notifications ─────────────────────────────────────────────
export const notifications = [
  { id:'n001', type:'donation',  unread:true,  title:'Donation Confirmed',         message:'Your ₱5,000 donation to the Scholarship Fund was received. Thank you!',     time:'2h ago',     action:'View Receipt' },
  { id:'n002', type:'campaign',  unread:true,  title:'Campaign Milestone Reached', message:'The Emergency Relief Fund reached 85% of its goal. Help us cross 100%!',  time:'5h ago',     action:'Donate Now' },
  { id:'n003', type:'event',     unread:true,  title:'Event Reminder',              message:'Alumni Grand Homecoming 2026 is in 3 days. You are registered!',           time:'Yesterday',  action:'View Event' },
  { id:'n004', type:'cert',      unread:false, title:'Certificate Ready',           message:'Your donation certificate for the Scholarship Fund is ready to download.',  time:'2d ago',     action:'Download' },
  { id:'n005', type:'campaign',  unread:false, title:'New Campaign Launched',       message:'Campus Sustainability Initiative is now live. Be among the first donors!', time:'3d ago',     action:'View Campaign' },
  { id:'n006', type:'match',     unread:false, title:'Matching Donation Active',    message:'A Platinum donor is matching all gifts to the Lab Equipment fund today!',   time:'4d ago',     action:'Donate Now' },
  { id:'n007', type:'event',     unread:false, title:'RSVP Confirmed',              message:'Your RSVP for the Batch 2015 Reunion has been confirmed.',                 time:'1w ago',     action: null },
];

// ── Donation History ──────────────────────────────────────────
export const donationHistory = [
  { id:'d001', campaignId:'c001', campaign:'AdDU Excellence Scholarship Fund', amount:5000,  date:'Feb 12, 2026', method:'GCash',  status:'Confirmed', cert:true  },
  { id:'d002', campaignId:'c003', campaign:'Student Emergency Relief Fund',    amount:2500,  date:'Jan 28, 2026', method:'Maya',   status:'Confirmed', cert:false },
  { id:'d003', campaignId:'c002', campaign:'New Science Laboratory Equipment', amount:3000,  date:'Jan 15, 2026', method:'Card',   status:'Confirmed', cert:true  },
  { id:'d004', campaignId:'c001', campaign:'AdDU Excellence Scholarship Fund', amount:2000,  date:'Dec 05, 2025', method:'GCash',  status:'Confirmed', cert:true  },
  { id:'d005', campaignId:'c005', campaign:'Sports & Athletics Program',       amount:1500,  date:'Nov 20, 2025', method:'Maya',   status:'Confirmed', cert:false },
  { id:'d006', campaignId:'c002', campaign:'New Science Laboratory Equipment', amount:1500,  date:'Oct 10, 2025', method:'Card',   status:'Confirmed', cert:true  },
];

// ── Admin Metrics ─────────────────────────────────────────────
export const adminMetrics = {
  totalRaised:    1414000,
  activeCampaigns: 5,
  totalDonors:     818,
  avgDonation:     1729,
  monthlyGrowth:  '+18%',
  newDonors:       42,
};
